CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id TEXT NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_messages_chat ON messages(chat_id, id);
CREATE TABLE IF NOT EXISTS notes (id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT NOT NULL, author TEXT, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS reminders (id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id TEXT NOT NULL, text TEXT NOT NULL, due_at INTEGER NOT NULL, repeat TEXT NOT NULL DEFAULT 'none', author TEXT, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_reminders_due ON reminders(due_at);
CREATE TABLE IF NOT EXISTS kb_docs (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, chunks INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE VIRTUAL TABLE IF NOT EXISTS kb_fts USING fts5(content, doc_id UNINDEXED, doc_name UNINDEXED, tokenize = "unicode61 remove_diacritics 2");
